spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: project

server:
  port: 8080

security:
  oauth2:
    client:
      client-id: spring-boot-oauth2-starter
      client-secret: secret
      scope: read,write
      auto-approve-scopes: '.*'